### ISSUE TITLE
Cards in Design System

### ISSUE THREAD

**Issue by bvelitchkine** [Bastien-and-Gauvain/monorepo#70]
Create these cards in the DS:

![Image](https://github.com/Bastien-and-Gauvain/monorepo/assets/45038783/720c34e1-6ed6-4f9b-a712-34be9288578e)

**Comment by GauvainThery** [comment]
Same comment here about the DS. We should create a card molecule that takes a button, an icon and potentially extra text but not create those specifically 🙏

**Comment by GauvainThery** [comment]
BTW, they should look like this?


![Image](https://github.com/Bastien-and-Gauvain/monorepo/assets/79575726/fb59c27e-a8de-41a4-92fe-83c3b470f727)


If so, I can update Figma properly, not the dirty mess I made 🙈
