### ISSUE TITLE
Mantras in DS

### ISSUE THREAD

**Issue by bvelitchkine** [Bastien-and-Gauvain/monorepo#73]
Implement this "mantra" component in the DS:

![Image](https://github.com/Bastien-and-Gauvain/monorepo/assets/45038783/93905e71-01e8-41ee-9465-e5b01a12b760)

The four current mantras are:
1. Recruitment is marketing, except that you don't sell a product, but the company.
2. Recruitment velocity increases success rates.
3. Personalized outreach increases response rates. Pay attention to details.
4. Constructive feedback turns unfit candidates into ambassadors.

**Comment by GauvainThery** [comment]
I don't understand why this is in the design system? I do get it for the typography but the content is business logic so shouldn't live in here but on the app IMHO

**Comment by bvelitchkine** [comment]
Because I'd like the mantra to change every 5s and choose one of the mantras at random. Mantras should be the same throughout the project, and I don't think we should deal with the animation logic anywhere else than the design system. Wdyt?

(and this would not be an atom, but a molecule, based on the typo you already created btw)
